/** @type {import('tailwindcss').Config} */
// Mirrort exact de eerdere CDN inline-config zodat de gebouwde CSS identiek rendert.
module.exports = {
  content: ['../index.html', '../collectie.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-bright': '#f8f1e4',
        'error': '#ba1a1a',
        'tertiary-fixed': '#d7e7cf',
        'on-surface-variant': '#4f4440',
        'on-primary-fixed-variant': '#5a4137',
        'surface-tint': '#74584e',
        'outline': '#827470',
        'surface': '#efe6d3',
        'inverse-on-surface': '#faefe2',
        'on-secondary-fixed': '#360f00',
        'on-tertiary-fixed': '#121f10',
        'surface-variant': '#ebe1d4',
        'inverse-primary': '#e3bfb2',
        'primary-fixed-dim': '#e3bfb2',
        'on-error-container': '#93000a',
        'tertiary': '#010801',
        'surface-dim': '#d9cbb0',
        'surface-container-low': '#e8dcc6',
        'on-secondary-container': '#783c20',
        'surface-container': '#e5d8c0',
        'on-error': '#ffffff',
        'outline-variant': '#d3c3be',
        'primary-fixed': '#ffdbce',
        'on-secondary': '#ffffff',
        'secondary': '#911818',
        'secondary-dark': '#6d1212',
        'on-surface': '#1f1b13',
        'on-tertiary-container': '#7b8b76',
        'secondary-fixed': '#ffdbcd',
        'on-primary-container': '#9f8074',
        'on-primary-fixed': '#2a170f',
        'secondary-container': '#feaa86',
        'surface-container-high': '#e0d3b9',
        'secondary-fixed-dim': '#ffb596',
        'inverse-surface': '#353027',
        'on-tertiary-fixed-variant': '#3c4b38',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#152213',
        'background': '#efe6d3',
        'primary-container': '#2e1a12',
        'error-container': '#ffdad6',
        'tertiary-fixed-dim': '#bbcbb3',
        'on-background': '#1f1b13',
        'on-secondary-fixed-variant': '#71361b',
        'on-primary': '#ffffff',
        'primary': '#100301',
        'surface-container-highest': '#ebe1d4',
        'surface-container-lowest': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        tussenruimte: '32px',
        'sectie-afstand': '120px',
        'marge-desktop': '64px',
        basis: '8px',
        'marge-mobiel': '24px',
      },
      fontFamily: {
        'label-sm': ['DM Sans'],
        'kop-lg-mobiel': ['EB Garamond'],
        'plattekunst-lg': ['DM Sans'],
        'kop-lg': ['EB Garamond'],
        'kop-md': ['EB Garamond'],
        'kop-xl': ['EB Garamond'],
        'plattekunst-md': ['DM Sans'],
      },
      fontSize: {
        'label-sm': ['13px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
        'kop-lg-mobiel': ['28px', { lineHeight: '1.2', fontWeight: '400' }],
        'plattekunst-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'kop-lg': ['32px', { lineHeight: '1.2', fontWeight: '400' }],
        'kop-md': ['24px', { lineHeight: '1.3', fontWeight: '500' }],
        'kop-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        'plattekunst-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
